version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
  postgres:
    image: postgres:latest
    container_name: quizizz_db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  redis:
    image: redis:latest
    container_name: quizizz_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass demo
    environment:
      - REDIS_PASSWORD=demo
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data: